### ISSUE TITLE
polys

### ISSUE THREAD

**Issue by lajnd** [Charestlab/pyGLMdenoise#39]
max_poly_deg = int(((data[0].shape[0] * self.tr) / 60) // 2) + 1
should be 
max_poly_deg = int(((data[0].shape[-1] * self.tr) / 60) // 2) + 1

since the input data has time in the last dimension

**Comment by lajnd** [comment]
in pyGlmdenoise.py

**Comment by iancharest** [comment]
is this fixed now? i'll close and reopen if not.
