### ISSUE TITLE
Python 3.6 + 3.7?

### ISSUE THREAD

**Issue by arokem** [Charestlab/pyGLMdenoise#63]
First of all, thanks for your work on this project. I have been dreaming of doing something like this, but never found the time and wherewithal, so I am very grateful that you did it! 

Second, is there any particular reason you are not testing on 3.6 and 3.7 yet?

**Comment by iancharest** [comment]
Hey Ariel, thanks ! I'm not sure I understand your question. We've developed this using 3.6 I believe. Are there specific unit tests you see missing that you think we should include? (we have a lot of these to write still..)

**Comment by iancharest** [comment]
ok I get it now. 
Did you stumble upon version problems with our code? any issues we should be aware of?

**Comment by arokem** [comment]
No issues on my end, but I thought that it would be polite to ask before showing up with a PR against your travis configuration :-)
